jenkins:

  authorizationStrategy: unsecured

  numExecutors: 4

  # allow html in build description for artifacts link
  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: false

appearance:
  pipelineGraphView:
    showGraphOnBuildPage: true

unclassified:
  timestamper:
    allPipelines: true

jobs:
  - script: >
      def pipeline = new File("/tmp/pipelines/ghaf-slim-demo-cached.groovy");
      if (pipeline.exists()) {
        pipelineJob('ghaf-slim-demo-cached') {
          definition {
            cps {
              script(pipeline.text)
            }
          }
        }
      }
  - script: >
      def pipeline = new File("/tmp/pipelines/ghaf-slim-demo-ephemeral.groovy");
      if (pipeline.exists()) {
        pipelineJob('ghaf-slim-demo-ephemeral') {
          definition {
            cps {
              script(pipeline.text)
            }
          }
        }
      }
  - script: >
      def pipeline = new File("/tmp/pipelines/ghaf-slim-demo-nix-build.groovy");
      if (pipeline.exists()) {
        pipelineJob('ghaf-slim-demo-nix-build') {
          definition {
            cps {
              script(pipeline.text)
            }
          }
        }
      }