jenkins:

  authorizationStrategy: unsecured

  numExecutors: 4

  # allow html in build description for artifacts link
  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: false

appearance:
  pipelineGraphView:
    showGraphOnBuildPage: true

unclassified:
  timestamper:
    allPipelines: true

jobs:
  - script: >
      pipelineJob('dummy') {
        definition {
          cps {
            script((new File("/tmp/pipelines/dummy.groovy")).text)
          }
        }
      }
  - script: >
      pipelineJob('ghaf-slim-demo-cached') {
        definition {
          cps {
            script((new File("/tmp/pipelines/ghaf-slim-demo-cached.groovy")).text)
          }
        }
      }
  - script: >
      pipelineJob('ghaf-slim-demo-ephemeral') {
        definition {
          cps {
            script((new File("/tmp/pipelines/ghaf-slim-demo-ephemeral.groovy")).text)
          }
        }
      }
