jobs:
  - script: >
      pipelineJob('on-prem-test-pipeline') {
        definition {
          cps {
            script(
            '''
            pipeline {
              agent any
              stages {
                stage('test sh') {
                  steps {
                    sh 'echo Testing'
                  }
                }
              }
            }
            '''
            )
          }
        }
      }