jobs:
  - script: >
      pipelineJob('ghaf-slim-demo') {
        definition {
          cps {
            script(
            '''
            def REPO_URL = 'https://github.com/tiiuae/ghaf-slim-demo/'
            def WORKDIR  = 'ghaf'
            properties([
              githubProjectProperty(displayName: '', projectUrlStr: REPO_URL),
              parameters([
                string(name: 'GITREF', defaultValue: 'main', description: 'Git reference (Commit/Branch/Tag)'),
                booleanParam(name: 'RELOAD_ONLY', defaultValue: true, description: 'Reload pipeline configuration without running any other stages')
              ])
            ])
            pipeline {
              agent { label 'built-in' }
              options {
                buildDiscarder(logRotator(numToKeepStr: '100'))
              }
              stages {
                stage('Reload only') {
                  when { expression { !params || params.RELOAD_ONLY } }
                  steps {
                    script {
                      currentBuild.result = 'ABORTED'
                      println 'Pipeline configuration reloaded'
                      env.ABORTED = 'true'
                    }
                  }
                }
                stage('Build') {
                  when { expression { env.ABORTED != 'true' } }
                  steps {
                    dir(WORKDIR) {
                      checkout scmGit(
                        branches: [[name: params.GITREF]],
                        extensions: [[$class: 'WipeWorkspace']],
                        userRemoteConfigs: [[url: REPO_URL]]
                      )
                      script {
                        // Single quotes in a script block needs to be escaped due
                        // to cps script block we are already in
                        sh \'\'\'
                          FILTER='^checks.x86_64-linux.*debug$'
                          OPTS='--remote build2.vedenemo.dev --no-download'
                          nix develop --command bash -c ".github/nix-fast-build.sh -f \'$FILTER\' -o \'$OPTS\'"
                        \'\'\'
                      }
                    }
                  }
                }
              }
            }
            '''
            )
          }
        }
      }