jobs:
  - script: >
      pipelineJob('dummy') {
        definition {
          cps {
            script(
            '''
            pipeline {
              agent any
              stages {
                stage('Test sh') {
                  steps {
                    sh 'echo Testing'
                    sh 'pwd'
                  }
                }
              }
            }
            '''
            )
          }
        }
      }