# pinned dependencies
bootstrap5-api:5.3.3-2 # 5.3.3-3 requires jenkins 2.496

# plugins
configuration-as-code
github
pipeline-build-step
pipeline-graph-view
pipeline-stage-view
pipeline-utility-steps
timestamper
workflow-aggregator
